<a href="https://colab.research.google.com/github/ClickDgo/Dashboard-Defunciones/blob/main/Proyecto_Maestr%C3%ADa_(Dise%C3%B1o_de_experimentos).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ============================================================
# ESTADÍSTICAS DESCRIPTIVAS DE DEFUNCIONES
# Análisis general y por causa
# ============================================================

# ------------------------------------------------------------
# 1. IMPORTAR LIBRERÍAS
# ------------------------------------------------------------

import pandas as pd
import numpy as np
from scipy import stats
from google.colab import files
from IPython.display import display, HTML
import io
import warnings

warnings.filterwarnings("ignore")


# ------------------------------------------------------------
# 2. CARGAR ARCHIVO CSV
# ------------------------------------------------------------

print("Selecciona el archivo CSV...")

uploaded = files.upload()

# Obtener nombre del archivo
nombre_archivo = list(uploaded.keys())[0]

print(f"\nArchivo cargado: {nombre_archivo}")


# ------------------------------------------------------------
# 3. LEER CSV
# ------------------------------------------------------------

# Intentar diferentes codificaciones
codificaciones = ["utf-8", "latin1", "cp1252"]

datos = None

for enc in codificaciones:
    try:
        datos = pd.read_csv(
            io.BytesIO(uploaded[nombre_archivo]),
            encoding=enc
        )
        print(f"Codificación utilizada: {enc}")
        break
    except UnicodeDecodeError:
        continue

if datos is None:
    raise ValueError("No fue posible leer el archivo con las codificaciones disponibles.")


# ------------------------------------------------------------
# 4. LIMPIEZA BÁSICA DE NOMBRES Y TEXTO
# ------------------------------------------------------------

datos.columns = datos.columns.str.strip()

columnas_texto = datos.select_dtypes(include="object").columns

for col in columnas_texto:
    datos[col] = (
        datos[col]
        .astype(str)
        .str.strip()
    )

# Convertir algunos valores que pudieran haber sido interpretados
# como texto "nan"
datos = datos.replace(["nan", "NaN", "None", ""], np.nan)


# ------------------------------------------------------------
# 5. VERIFICACIÓN DE COLUMNAS
# ------------------------------------------------------------

columnas_necesarias = [
    "Causa",
    "Sexo",
    "AfroMexicanos",
    "CondicionIndigena",
    "Edad",
    "Escolaridad",
    "Ocupacion",
    "Ocupacion_Ampliado",
    "EstadoCivil"
]

faltantes = [
    col for col in columnas_necesarias
    if col not in datos.columns
]

if faltantes:
    raise ValueError(
        "Faltan las siguientes columnas en el archivo:\n"
        + "\n".join(f"- {x}" for x in faltantes)
    )


# ------------------------------------------------------------
# 6. INFORMACIÓN GENERAL DE LA BASE
# ------------------------------------------------------------

N_TOTAL = len(datos)

numero_causas = datos["Causa"].nunique()

causas = (
    datos["Causa"]
    .dropna()
    .value_counts()
    .index
    .tolist()
)


# ------------------------------------------------------------
# 7. FUNCIONES PARA TABLAS CATEGÓRICAS
# ------------------------------------------------------------

def tabla_categorica(df, columna):

    serie = df[columna].dropna()

    tabla = (
        serie
        .value_counts()
        .rename_axis("Categoría")
        .reset_index(name="Total")
    )

    tabla["Porcentaje"] = (
        tabla["Total"] / tabla["Total"].sum() * 100
    )

    tabla["Porcentaje"] = tabla["Porcentaje"].round(2)

    # Agregar total
    fila_total = pd.DataFrame({
        "Categoría": ["TOTAL"],
        "Total": [tabla["Total"].sum()],
        "Porcentaje": [100.00]
    })

    tabla = pd.concat(
        [tabla, fila_total],
        ignore_index=True
    )

    return tabla


# ------------------------------------------------------------
# 8. FUNCIÓN PARA ESTADÍSTICAS DE EDAD
# ------------------------------------------------------------

def estadisticas_edad(df):

    edad = pd.to_numeric(
        df["Edad"],
        errors="coerce"
    ).dropna()

    n = len(edad)

    if n == 0:
        return None

    q1 = edad.quantile(0.25)
    mediana = edad.quantile(0.50)
    q3 = edad.quantile(0.75)

    media = edad.mean()
    desviacion = edad.std()
    minimo = edad.min()
    maximo = edad.max()

    rango = maximo - minimo
    iqr = q3 - q1

    asimetria = stats.skew(edad, bias=False)
    curtosis = stats.kurtosis(
        edad,
        fisher=True,
        bias=False
    )

    # --------------------------------------------------------
    # Prueba de normalidad para muestras grandes
    # D'Agostino-Pearson
    # --------------------------------------------------------

    # La prueba requiere al menos 8 observaciones
    if n >= 8:

        statistic_normalidad, p_normalidad = (
            stats.normaltest(edad)
        )

        if p_normalidad < 0.05:
            conclusion_normalidad = (
                "Se rechaza la normalidad"
            )
        else:
            conclusion_normalidad = (
                "No se rechaza la normalidad"
            )

    else:

        statistic_normalidad = np.nan
        p_normalidad = np.nan

        conclusion_normalidad = (
            "No es posible aplicar la prueba"
        )

    resumen = pd.DataFrame({
        "Estadístico": [
            "N",
            "Media",
            "Desviación estándar",
            "Mínimo",
            "Q1",
            "Mediana",
            "Q3",
            "Máximo",
            "Rango",
            "IQR",
            "Asimetría",
            "Curtosis",
            "D'Agostino-Pearson",
            "p-valor normalidad"
        ],

        "Valor": [
            n,
            media,
            desviacion,
            minimo,
            q1,
            mediana,
            q3,
            maximo,
            rango,
            iqr,
            asimetria,
            curtosis,
            statistic_normalidad,
            p_normalidad
        ]
    })

    return resumen, conclusion_normalidad


# ------------------------------------------------------------
# 9. FUNCIÓN PARA TABLA DE DISTRIBUCIÓN DE EDADES
# ------------------------------------------------------------

def tabla_edades(df):

    edad = pd.to_numeric(
        df["Edad"],
        errors="coerce"
    ).dropna()

    tabla = (
        edad
        .value_counts()
        .sort_index()
        .rename_axis("Edad")
        .reset_index(name="Total")
    )

    tabla["Porcentaje"] = (
        tabla["Total"] / tabla["Total"].sum() * 100
    )

    tabla["Porcentaje"] = tabla["Porcentaje"].round(2)

    fila_total = pd.DataFrame({
        "Edad": ["TOTAL"],
        "Total": [tabla["Total"].sum()],
        "Porcentaje": [100.00]
    })

    tabla = pd.concat(
        [tabla, fila_total],
        ignore_index=True
    )

    return tabla


# ------------------------------------------------------------
# 10. GUARDAR RESULTADOS EN OBJETO
# ------------------------------------------------------------

resultados = {}

variables_categoricas = [
    "Sexo",
    "AfroMexicanos",
    "CondicionIndigena",
    "Escolaridad",
    "Ocupacion",
    "Ocupacion_Ampliado",
    "EstadoCivil"
]


# ============================================================
# 11. ESTADÍSTICAS GENERALES
# ============================================================

resultados["GENERAL"] = {}

for variable in variables_categoricas:

    resultados["GENERAL"][variable] = (
        tabla_categorica(datos, variable)
    )

resultados["GENERAL"]["Edad"] = {
    "estadisticas": estadisticas_edad(datos),
    "distribucion": tabla_edades(datos)
}


# ============================================================
# 12. ESTADÍSTICAS POR CAUSA
# ============================================================

for causa in causas:

    df_causa = datos[
        datos["Causa"] == causa
    ].copy()

    resultados[causa] = {
        "N": len(df_causa)
    }

    # Variables categóricas
    for variable in variables_categoricas:

        resultados[causa][variable] = (
            tabla_categorica(
                df_causa,
                variable
            )
        )

    # Edad
    resultados[causa]["Edad"] = {
        "estadisticas": estadisticas_edad(
            df_causa
        ),
        "distribucion": tabla_edades(
            df_causa
        )
    }


# ============================================================
# 13. GENERAR REPORTE FINAL
# ============================================================

print("\n")
print("=" * 80)
print("REPORTE ESTADÍSTICO DESCRIPTIVO")
print("=" * 80)


# ------------------------------------------------------------
# REPORTE GENERAL
# ------------------------------------------------------------

print("\n")
print("1. ESTADÍSTICAS GENERALES")
print("-" * 80)

print(f"\nTotal general de registros: {N_TOTAL:,}")
print(f"Número de causas: {numero_causas}")


for variable in variables_categoricas:

    print("\n")
    print(f"--- {variable} ---")

    display(
        resultados["GENERAL"][variable]
        .style
        .format({
            "Porcentaje": "{:.2f}%"
        })
    )


# ------------------------------------------------------------
# EDAD GENERAL
# ------------------------------------------------------------

print("\n")
print("--- EDAD: ESTADÍSTICOS DESCRIPTIVOS ---")

resumen_edad, conclusion = (
    resultados["GENERAL"]["Edad"]["estadisticas"]
)

display(
    resumen_edad.style.format({
        "Valor": "{:.4f}"
    })
)

print(
    f"Interpretación de normalidad: {conclusion}"
)

print("\n--- DISTRIBUCIÓN DE EDAD ---")

display(
    resultados["GENERAL"]["Edad"]["distribucion"]
    .style
    .format({
        "Porcentaje": "{:.2f}%"
    })
)


# ============================================================
# 14. REPORTE POR CAUSA
# ============================================================

print("\n\n")
print("=" * 80)
print("ESTADÍSTICAS DESCRIPTIVAS POR CAUSA")
print("=" * 80)


for i, causa in enumerate(causas, start=1):

    df_causa = datos[
        datos["Causa"] == causa
    ]

    print("\n")
    print("=" * 80)
    print(f"CAUSA {i}")
    print("=" * 80)

    print(f"\n{causa}")
    print(f"\nTotal de defunciones: {len(df_causa):,}")


    # --------------------------------------------------------
    # Variables categóricas
    # --------------------------------------------------------

    for variable in variables_categoricas:

        print("\n")
        print(f"--- {variable} ---")

        display(
            resultados[causa][variable]
            .style
            .format({
                "Porcentaje": "{:.2f}%"
            })
        )


    # --------------------------------------------------------
    # Edad
    # --------------------------------------------------------

    print("\n")
    print("--- EDAD: ESTADÍSTICOS DESCRIPTIVOS ---")

    resumen_edad, conclusion = (
        resultados[causa]["Edad"]["estadisticas"]
    )

    display(
        resumen_edad.style.format({
            "Valor": "{:.4f}"
        })
    )

    print(
        f"Interpretación de normalidad: {conclusion}"
    )


    print("\n--- DISTRIBUCIÓN DE EDAD ---")

    display(
        resultados[causa]["Edad"]["distribucion"]
        .style
        .format({
            "Porcentaje": "{:.2f}%"
        })
    )


# ============================================================
# 15. RESUMEN DE TAMAÑOS DE MUESTRA
# ============================================================

print("\n\n")
print("=" * 80)
print("RESUMEN DE LA MUESTRA")
print("=" * 80)

resumen_muestra = (
    datos["Causa"]
    .value_counts()
    .rename_axis("Causa")
    .reset_index(name="Total")
)

resumen_muestra["Porcentaje"] = (
    resumen_muestra["Total"]
    / resumen_muestra["Total"].sum()
    * 100
)

resumen_muestra["Porcentaje"] = (
    resumen_muestra["Porcentaje"].round(2)
)

fila_total = pd.DataFrame({
    "Causa": ["TOTAL GENERAL"],
    "Total": [resumen_muestra["Total"].sum()],
    "Porcentaje": [100.00]
})

resumen_muestra = pd.concat(
    [resumen_muestra, fila_total],
    ignore_index=True
)

display(
    resumen_muestra.style.format({
        "Porcentaje": "{:.2f}%"
    })
)

print("\n")
print("=" * 80)
print("FIN DEL REPORTE ESTADÍSTICO")
print("=" * 80)

Selecciona el archivo CSV...

Saving Defunciones.csv to Defunciones.csv

Archivo cargado: Defunciones.csv
Codificación utilizada: latin1


================================================================================
REPORTE ESTADÍSTICO DESCRIPTIVO
================================================================================


1. ESTADÍSTICAS GENERALES
--------------------------------------------------------------------------------

Total general de registros: 75,603
Número de causas: 3


--- Sexo ---

--- AfroMexicanos ---

--- CondicionIndigena ---

--- Escolaridad ---

--- Ocupacion ---

--- Ocupacion_Ampliado ---

--- EstadoCivil ---

--- EDAD: ESTADÍSTICOS DESCRIPTIVOS ---

Interpretación de normalidad: Se rechaza la normalidad

--- DISTRIBUCIÓN DE EDAD ---

================================================================================
ESTADÍSTICAS DESCRIPTIVAS POR CAUSA
================================================================================


================================================================================
CAUSA 1
================================================================================

Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas

Total de defunciones: 35,843


--- Sexo ---

--- AfroMexicanos ---

--- CondicionIndigena ---

--- Escolaridad ---

--- Ocupacion ---

--- Ocupacion_Ampliado ---

--- EstadoCivil ---

--- EDAD: ESTADÍSTICOS DESCRIPTIVOS ---

Interpretación de normalidad: Se rechaza la normalidad

--- DISTRIBUCIÓN DE EDAD ---

================================================================================
CAUSA 2
================================================================================

Neumonia, no especificada

Total de defunciones: 28,030


--- Sexo ---

--- AfroMexicanos ---

--- CondicionIndigena ---

--- Escolaridad ---

--- Ocupacion ---

--- Ocupacion_Ampliado ---

--- EstadoCivil ---

--- EDAD: ESTADÍSTICOS DESCRIPTIVOS ---

Interpretación de normalidad: Se rechaza la normalidad

--- DISTRIBUCIÓN DE EDAD ---

================================================================================
CAUSA 3
================================================================================

Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras

Total de defunciones: 11,730


--- Sexo ---

--- AfroMexicanos ---

--- CondicionIndigena ---

--- Escolaridad ---

--- Ocupacion ---

--- Ocupacion_Ampliado ---

--- EstadoCivil ---

--- EDAD: ESTADÍSTICOS DESCRIPTIVOS ---

Interpretación de normalidad: Se rechaza la normalidad

--- DISTRIBUCIÓN DE EDAD ---

================================================================================
RESUMEN DE LA MUESTRA
================================================================================

================================================================================
FIN DEL REPORTE ESTADÍSTICO
================================================================================

In [ ]:
# ============================================================
# ANÁLISIS DE JI-CUADRADA DE INDEPENDENCIA
# CAUSA vs VARIABLES CATEGÓRICAS
#
# Incluye:
#   1. Chi-cuadrada global
#   2. p-valor
#   3. V de Cramér
#   4. Tablas de contingencia
#   5. Residuales estandarizados ajustados
#   6. Identificación de las categorías asociadas
#   7. Corrección por comparaciones múltiples
#
# NO GUARDA ARCHIVOS
# ============================================================


# ============================================================
# 1. LIBRERÍAS
# ============================================================

import pandas as pd
import numpy as np

from scipy.stats import (
    chi2_contingency,
    norm
)

from statsmodels.stats.multitest import multipletests

from google.colab import files

from IPython.display import display

import io
import warnings

warnings.filterwarnings("ignore")


# ============================================================
# 2. CARGAR ARCHIVO
# ============================================================

print("Selecciona el archivo CSV...")

uploaded = files.upload()

nombre_archivo = list(uploaded.keys())[0]

print(f"\nArchivo cargado: {nombre_archivo}")


# ============================================================
# 3. LEER ARCHIVO
# ============================================================

codificaciones = [
    "utf-8",
    "latin1",
    "cp1252"
]

datos = None

for enc in codificaciones:

    try:

        datos = pd.read_csv(
            io.BytesIO(
                uploaded[nombre_archivo]
            ),
            encoding=enc
        )

        print(
            f"Codificación utilizada: {enc}"
        )

        break

    except UnicodeDecodeError:

        continue


if datos is None:

    raise ValueError(
        "No fue posible leer el archivo."
    )


# ============================================================
# 4. LIMPIEZA BÁSICA
# ============================================================

datos.columns = (
    datos.columns
    .str.strip()
)


columnas_texto = (
    datos
    .select_dtypes(include="object")
    .columns
)


for col in columnas_texto:

    datos[col] = (
        datos[col]
        .astype(str)
        .str.strip()
    )


datos = datos.replace(
    [
        "nan",
        "NaN",
        "None",
        ""
    ],
    np.nan
)


# ============================================================
# 5. VARIABLES CATEGÓRICAS
# ============================================================

columnas_categoricas = [

    "Sexo",

    "AfroMexicanos",

    "CondicionIndigena",

    "Escolaridad",

    "Ocupacion",

    "Ocupacion_Ampliado",

    "EstadoCivil"

]


# ============================================================
# 6. VERIFICAR COLUMNAS
# ============================================================

columnas_necesarias = [
    "Causa"
] + columnas_categoricas


faltantes = [
    col
    for col in columnas_necesarias
    if col not in datos.columns
]


if faltantes:

    raise ValueError(
        "Faltan las siguientes columnas:\n"
        +
        "\n".join(
            f"- {x}"
            for x in faltantes
        )
    )


# ============================================================
# 7. CONFIGURACIÓN
# ============================================================

ALFA = 0.05


# ============================================================
# 8. FUNCIÓN V DE CRAMÉR
# ============================================================

def cramers_v(
    tabla,
    chi2
):

    n = tabla.to_numpy().sum()

    filas, columnas = (
        tabla.shape
    )

    minimo = min(
        filas - 1,
        columnas - 1
    )

    if (
        minimo <= 0
        or n <= 0
    ):

        return np.nan

    return np.sqrt(
        chi2 /
        (
            n * minimo
        )
    )


# ============================================================
# 9. INTERPRETACIÓN DE V DE CRAMÉR
# ============================================================

def interpretar_v(v):

    if pd.isna(v):

        return "No calculable"

    elif v < 0.10:

        return "Muy débil"

    elif v < 0.20:

        return "Débil"

    elif v < 0.30:

        return "Moderada"

    elif v < 0.50:

        return "Fuerte"

    else:

        return "Muy fuerte"


# ============================================================
# 10. FUNCIÓN PARA ANALIZAR LAS CELDAS
# ============================================================

def analizar_celdas(
    tabla,
    esperados
):

    observados = (
        tabla
        .to_numpy()
        .astype(float)
    )


    # --------------------------------------------------------
    # Totales
    # --------------------------------------------------------

    totales_fila = (
        observados.sum(
            axis=1,
            keepdims=True
        )
    )

    totales_columna = (
        observados.sum(
            axis=0,
            keepdims=True
        )
    )

    n = observados.sum()


    # --------------------------------------------------------
    # Residuales estandarizados ajustados
    # --------------------------------------------------------

    proporciones_fila = (
        totales_fila / n
    )

    proporciones_columna = (
        totales_columna / n
    )


    # Residual ajustado:

    residuales = (
        (
            observados
            - esperados
        )
        /
        np.sqrt(
            esperados
            *
            (
                1
                - proporciones_fila
            )
            *
            (
                1
                - proporciones_columna
            )
        )
    )


    # --------------------------------------------------------
    # p-valor de cada celda
    # --------------------------------------------------------

    p_celdas = (
        2
        *
        norm.sf(
            np.abs(residuales)
        )
    )


    # --------------------------------------------------------
    # Crear dataframe
    # --------------------------------------------------------

    filas = []

    nombres_filas = (
        tabla.index.tolist()
    )

    nombres_columnas = (
        tabla.columns.tolist()
    )


    for i, causa in enumerate(
        nombres_filas
    ):

        for j, categoria in enumerate(
            nombres_columnas
        ):

            observado = (
                observados[i, j]
            )

            esperado = (
                esperados[i, j]
            )

            residual = (
                residuales[i, j]
            )

            p = (
                p_celdas[i, j]
            )


            # Porcentaje de la categoría
            # dentro de la causa

            total_causa = (
                observados[i, :].sum()
            )

            porcentaje_fila = (
                observado
                /
                total_causa
                *
                100
            )


            # Dirección de la asociación

            if residual > 0:

                direccion = (
                    "Mayor de lo esperado"
                )

            elif residual < 0:

                direccion = (
                    "Menor de lo esperado"
                )

            else:

                direccion = (
                    "Igual a lo esperado"
                )


            filas.append({

                "Causa":
                    causa,

                "Categoría":
                    categoria,

                "Observado":
                    observado,

                "Esperado":
                    esperado,

                "Residual":
                    residual,

                "p_celda":
                    p,

                "Porcentaje_dentro_Causa":
                    porcentaje_fila,

                "Dirección":
                    direccion

            })


    resultado = pd.DataFrame(
        filas
    )


    # --------------------------------------------------------
    # Corrección de Holm
    # --------------------------------------------------------

    if len(resultado) > 0:

        (
            rechazo,
            p_ajustado,
            _,
            _
        ) = multipletests(
            resultado["p_celda"],
            alpha=ALFA,
            method="holm"
        )

        resultado[
            "p_ajustado"
        ] = p_ajustado

        resultado[
            "Significativa"
        ] = rechazo

    else:

        resultado[
            "p_ajustado"
        ] = []

        resultado[
            "Significativa"
        ] = []


    return resultado


# ============================================================
# 11. FUNCIÓN PRINCIPAL DE CHI-CUADRADA
# ============================================================

def prueba_chi_cuadrada(
    df,
    variable
):

    # --------------------------------------------------------
    # Seleccionar datos válidos
    # --------------------------------------------------------

    temp = df[
        [
            "Causa",
            variable
        ]
    ].dropna()


    # --------------------------------------------------------
    # Tabla de contingencia
    # --------------------------------------------------------

    tabla = pd.crosstab(
        temp["Causa"],
        temp[variable]
    )


    # --------------------------------------------------------
    # Verificar dimensiones
    # --------------------------------------------------------

    if (
        tabla.shape[0] < 2
        or tabla.shape[1] < 2
    ):

        return None


    # --------------------------------------------------------
    # Chi-cuadrada
    # --------------------------------------------------------

    (
        chi2,
        p,
        gl,
        esperados
    ) = chi2_contingency(
        tabla,
        correction=False
    )


    # --------------------------------------------------------
    # V de Cramér
    # --------------------------------------------------------

    v = cramers_v(
        tabla,
        chi2
    )


    # --------------------------------------------------------
    # Frecuencias esperadas
    # --------------------------------------------------------

    esperados = np.array(
        esperados
    )


    porcentaje_menor_5 = (
        (
            esperados < 5
        ).sum()
        /
        esperados.size
        *
        100
    )


    minimo_esperado = (
        esperados.min()
    )


    # --------------------------------------------------------
    # Analizar celdas
    # --------------------------------------------------------

    celdas = analizar_celdas(
        tabla,
        esperados
    )


    # --------------------------------------------------------
    # Resultado global
    # --------------------------------------------------------

    resultado = {

        "Variable":
            variable,

        "N":
            len(temp),

        "Chi2":
            chi2,

        "gl":
            gl,

        "p":
            p,

        "V_Cramer":
            v,

        "Interpretacion_V":
            interpretar_v(v),

        "Celdas_esperadas_<5_%":
            porcentaje_menor_5,

        "Min_esperado":
            minimo_esperado,

        "Significativa":
            p < ALFA

    }


    return (
        resultado,
        tabla,
        celdas
    )


# ============================================================
# 12. EJECUTAR TODAS LAS PRUEBAS
# ============================================================

resultados_chi = []

tablas_contingencia = {}

resultados_celdas = {}


for variable in columnas_categoricas:

    resultado = prueba_chi_cuadrada(
        datos,
        variable
    )


    if resultado is None:

        continue


    (
        resultado_dict,
        tabla,
        celdas
    ) = resultado


    resultados_chi.append(
        resultado_dict
    )


    tablas_contingencia[
        variable
    ] = tabla


    resultados_celdas[
        variable
    ] = celdas


# ============================================================
# 13. DATAFRAME GENERAL
# ============================================================

resultados_chi = pd.DataFrame(
    resultados_chi
)


# ============================================================
# 14. ORDENAR POR P-VALOR
# ============================================================

resultados_chi = (
    resultados_chi
    .sort_values(
        by="p"
    )
    .reset_index(
        drop=True
    )
)


# ============================================================
# 15. SELECCIONAR SOLAMENTE LAS SIGNIFICATIVAS
# ============================================================

significativas = resultados_chi[
    resultados_chi[
        "Significativa"
    ]
].copy()


# ============================================================
# 16. REPORTE GENERAL
# ============================================================

print("\n")

print("=" * 100)

print(
    "ANÁLISIS DE INDEPENDENCIA"
)

print(
    "CAUSA vs VARIABLES CATEGÓRICAS"
)

print("=" * 100)


print(
    f"\nNivel de significancia: "
    f"α = {ALFA}"
)


print(
    f"\nNúmero de pruebas realizadas: "
    f"{len(resultados_chi)}"
)


print(
    f"Número de asociaciones significativas: "
    f"{len(significativas)}"
)


# ============================================================
# 17. TABLA GENERAL DE ASOCIACIONES SIGNIFICATIVAS
# ============================================================

print("\n")

print("=" * 100)

print(
    "1. ASOCIACIONES SIGNIFICATIVAS"
)

print("=" * 100)


if len(significativas) == 0:

    print(
        "\nNo se encontraron asociaciones "
        "estadísticamente significativas."
    )

else:

    tabla_resumen = significativas[
        [
            "Variable",
            "N",
            "Chi2",
            "gl",
            "p",
            "V_Cramer",
            "Interpretacion_V",
            "Celdas_esperadas_<5_%",
            "Min_esperado"
        ]
    ].copy()


    tabla_resumen = (
        tabla_resumen
        .rename(
            columns={

                "Chi2":
                    "χ²",

                "V_Cramer":
                    "V de Cramér",

                "Interpretacion_V":
                    "Magnitud",

                "Celdas_esperadas_<5_%":
                    "Celdas esperadas <5 (%)",

                "Min_esperado":
                    "Mínimo esperado"

            }
        )
    )


    display(
        tabla_resumen.style.format({

            "N":
                "{:,.0f}",

            "χ²":
                "{:,.3f}",

            "p":
                "{:.6g}",

            "V de Cramér":
                "{:.3f}",

            "Celdas esperadas <5 (%)":
                "{:.2f}%",

            "Mínimo esperado":
                "{:.3f}"

        })
    )


# ============================================================
# 18. ANÁLISIS DETALLADO DE CADA VARIABLE SIGNIFICATIVA
# ============================================================

print("\n")

print("=" * 100)

print(
    "2. ¿QUÉ CATEGORÍAS ESTÁN RELACIONADAS CON CADA CAUSA?"
)

print("=" * 100)


for _, fila in significativas.iterrows():

    variable = fila[
        "Variable"
    ]


    print("\n")

    print("#" * 100)

    print(
        f"CAUSA × {variable}"
    )

    print("#" * 100)


    print(
        f"\nχ² = "
        f"{fila['Chi2']:.3f}"
    )

    print(
        f"gl = "
        f"{int(fila['gl'])}"
    )

    print(
        f"p = "
        f"{fila['p']:.6g}"
    )

    print(
        f"V de Cramér = "
        f"{fila['V_Cramer']:.3f}"
    )

    print(
        f"Magnitud = "
        f"{fila['Interpretacion_V']}"
    )


    # --------------------------------------------------------
    # Tabla de contingencia
    # --------------------------------------------------------

    print(
        "\nTabla de frecuencias observadas:"
    )


    tabla = (
        tablas_contingencia[
            variable
        ]
        .copy()
    )


    tabla["TOTAL"] = (
        tabla.sum(
            axis=1
        )
    )


    fila_total = (
        tabla.sum(
            axis=0
        )
        .to_frame()
        .T
    )


    fila_total.index = [
        "TOTAL"
    ]


    tabla = pd.concat(
        [
            tabla,
            fila_total
        ]
    )


    display(
        tabla
    )


    # --------------------------------------------------------
    # Todas las celdas con sus residuales
    # --------------------------------------------------------

    celdas = (
        resultados_celdas[
            variable
        ]
        .copy()
    )


    # --------------------------------------------------------
    # Solamente categorías significativas
    # después de corrección de Holm
    # --------------------------------------------------------

    celdas_significativas = celdas[
        celdas[
            "Significativa"
        ]
    ].copy()


    # --------------------------------------------------------
    # Ordenar por magnitud absoluta del residual
    # --------------------------------------------------------

    celdas_significativas[
        "Abs_Residual"
    ] = np.abs(
        celdas_significativas[
            "Residual"
        ]
    )


    celdas_significativas = (
        celdas_significativas
        .sort_values(
            by="Abs_Residual",
            ascending=False
        )
    )


    print(
        "\nCategorías específicamente asociadas:"
    )


    if len(
        celdas_significativas
    ) == 0:

        print(
            "\nNinguna celda individual "
            "resultó significativa después "
            "de la corrección de Holm."
        )

    else:

        tabla_categorias = (
            celdas_significativas[
                [
                    "Causa",
                    "Categoría",
                    "Observado",
                    "Esperado",
                    "Residual",
                    "p_celda",
                    "p_ajustado",
                    "Porcentaje_dentro_Causa",
                    "Dirección"
                ]
            ]
            .copy()
        )


        tabla_categorias = (
            tabla_categorias
            .rename(
                columns={

                    "Observado":
                        "Observado",

                    "Esperado":
                        "Esperado",

                    "Residual":
                        "Residual ajustado",

                    "p_celda":
                        "p celda",

                    "p_ajustado":
                        "p ajustado",

                    "Porcentaje_dentro_Causa":
                        "% dentro de la causa",

                    "Dirección":
                        "Relación"

                }
            )
        )


        display(
            tabla_categorias.style.format({

                "Observado":
                    "{:,.0f}",

                "Esperado":
                    "{:,.2f}",

                "Residual ajustado":
                    "{:.3f}",

                "p celda":
                    "{:.6g}",

                "p ajustado":
                    "{:.6g}",

                "% dentro de la causa":
                    "{:.2f}%"

            })
        )


        # ----------------------------------------------------
        # Explicación textual de las categorías
        # ----------------------------------------------------

        print(
            "\nInterpretación de las categorías:"
        )


        for _, celda in (
            celdas_significativas
            .iterrows()
        ):

            causa = celda[
                "Causa"
            ]

            categoria = celda[
                "Categoría"
            ]

            observado = celda[
                "Observado"
            ]

            esperado = celda[
                "Esperado"
            ]

            residual = celda[
                "Residual"
            ]

            porcentaje = celda[
                "Porcentaje_dentro_Causa"
            ]

            if residual > 0:

                print(
                    f"\n• {causa}"
                    f" — {variable}: "
                    f"'{categoria}'"
                    f" → aparece MÁS veces "
                    f"de lo esperado."
                    f" Observado = "
                    f"{observado:,.0f};"
                    f" esperado = "
                    f"{esperado:,.2f};"
                    f" {porcentaje:.2f}% "
                    f"dentro de esta causa."
                )

            elif residual < 0:

                print(
                    f"\n• {causa}"
                    f" — {variable}: "
                    f"'{categoria}'"
                    f" → aparece MENOS veces "
                    f"de lo esperado."
                    f" Observado = "
                    f"{observado:,.0f};"
                    f" esperado = "
                    f"{esperado:,.2f};"
                    f" {porcentaje:.2f}% "
                    f"dentro de esta causa."
                )


# ============================================================
# 19. RESUMEN FINAL POR CAUSA
# ============================================================

print("\n")

print("=" * 100)

print(
    "3. RESUMEN: CATEGORÍAS ASOCIADAS A CADA CAUSA"
)

print("=" * 100)


if len(significativas) == 0:

    print(
        "\nNo existen asociaciones significativas "
        "para resumir."
    )

else:

    for causa in datos[
        "Causa"
    ].dropna().unique():

        print("\n")

        print("-" * 100)

        print(
            f"CAUSA: {causa}"
        )

        print("-" * 100)


        encontro = False


        for variable in columnas_categoricas:

            if variable not in resultados_celdas:

                continue


            celdas = resultados_celdas[
                variable
            ]


            celdas_causa = celdas[
                (
                    celdas["Causa"]
                    == causa
                )
                &
                (
                    celdas["Significativa"]
                    == True
                )
            ]


            if len(
                celdas_causa
            ) == 0:

                continue


            # Sólo incluimos la variable si
            # su Chi-cuadrada global fue significativa

            resultado_variable = (
                significativas[
                    significativas[
                        "Variable"
                    ]
                    == variable
                ]
            )


            if len(
                resultado_variable
            ) == 0:

                continue


            encontro = True


            print(
                f"\n{variable}:"
            )


            for _, celda in (
                celdas_causa
                .sort_values(
                    "Residual",
                    ascending=False
                )
                .iterrows()
            ):

                categoria = celda[
                    "Categoría"
                ]

                residual = celda[
                    "Residual"
                ]

                observado = celda[
                    "Observado"
                ]

                esperado = celda[
                    "Esperado"
                ]


                if residual > 0:

                    print(
                        f"   ↑ {categoria}"
                        f" | observado: "
                        f"{observado:,.0f}"
                        f" | esperado: "
                        f"{esperado:,.2f}"
                        f" | residual: "
                        f"{residual:.2f}"
                    )

                else:

                    print(
                        f"   ↓ {categoria}"
                        f" | observado: "
                        f"{observado:,.0f}"
                        f" | esperado: "
                        f"{esperado:,.2f}"
                        f" | residual: "
                        f"{residual:.2f}"
                    )


        if not encontro:

            print(
                "\nNo se identificaron "
                "categorías individuales "
                "significativamente asociadas "
                "con esta causa."
            )


# ============================================================
# 20. RESUMEN GENERAL
# ============================================================

print("\n")

print("=" * 100)

print(
    "ANÁLISIS TERMINADO"
)

print("=" * 100)

print(
    "\nSe analizaron todas las variables categóricas "
    "contra Causa."
)

print(
    "El reporte principal conserva únicamente "
    "las asociaciones globales con p < 0.05."
)

print(
    "\nPara las asociaciones significativas, "
    "se identificaron las categorías específicas "
    "mediante residuales estandarizados ajustados "
    "y corrección de Holm por comparaciones múltiples."
)

print(
    "\nNo se generaron ni guardaron archivos."
)

Selecciona el archivo CSV...

Saving Defunciones.csv to Defunciones (2).csv

Archivo cargado: Defunciones (2).csv
Codificación utilizada: latin1


====================================================================================================
ANÁLISIS DE INDEPENDENCIA
CAUSA vs VARIABLES CATEGÓRICAS
====================================================================================================

Nivel de significancia: α = 0.05

Número de pruebas realizadas: 7
Número de asociaciones significativas: 7


====================================================================================================
1. ASOCIACIONES SIGNIFICATIVAS
====================================================================================================

====================================================================================================
2. ¿QUÉ CATEGORÍAS ESTÁN RELACIONADAS CON CADA CAUSA?
====================================================================================================


####################################################################################################
CAUSA × Sexo
####################################################################################################

χ² = 6512.978
gl = 2
p = 0
V de Cramér = 0.294
Magnitud = Moderada

Tabla de frecuencias observadas:

Sexo                                                Hombre  Mujer  TOTAL
Agresion Con Disparo De Otras Armas De Fuego, Y...   10791    939  11730
Diabetes Mellitus Tipo 2, Con Otras Complicacio...   18121  17722  35843
Neumonia, no especificada                            15360  12670  28030
TOTAL                                                44272  31331  75603

Categorías específicamente asociadas:

Interpretación de las categorías:

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Sexo: 'Hombre' → aparece MÁS veces de lo esperado. Observado = 10,791; esperado = 6,868.91; 91.99% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Sexo: 'Mujer' → aparece MENOS veces de lo esperado. Observado = 939; esperado = 4,861.09; 8.01% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Sexo: 'Hombre' → aparece MENOS veces de lo esperado. Observado = 18,121; esperado = 20,989.13; 50.56% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Sexo: 'Mujer' → aparece MÁS veces de lo esperado. Observado = 17,722; esperado = 14,853.87; 49.44% dentro de esta causa.

• Neumonia, no especificada — Sexo: 'Hombre' → aparece MENOS veces de lo esperado. Observado = 15,360; esperado = 16,413.95; 54.80% dentro de esta causa.

• Neumonia, no especificada — Sexo: 'Mujer' → aparece MÁS veces de lo esperado. Observado = 12,670; esperado = 11,616.05; 45.20% dentro de esta causa.


####################################################################################################
CAUSA × Escolaridad
####################################################################################################

χ² = 11073.971
gl = 22
p = 0
V de Cramér = 0.271
Magnitud = Moderada

Tabla de frecuencias observadas:

Escolaridad,Bachillerato o preparatoria completo,Bachillerato o preparatoria incompleto,No aplica a menores de 3,No especificado,Posgrado,Preescolar,Primaria completa,Primaria incompleta,Profesional,Secundaria completa,Secundaria incompleta,Sin escolaridad,TOTAL
"Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras",1641,797,5,175,47,17,2193,887,882,3825,945,316,11730
"Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas",2128,401,1,836,124,32,9583,8957,2567,4159,599,6456,35843
"Neumonia, no especificada",2101,462,815,1127,240,70,5915,6321,2537,3391,664,4387,28030
TOTAL,5870,1660,821,2138,411,119,17691,16165,5986,11375,2208,11159,75603

Categorías específicamente asociadas:

Interpretación de las categorías:

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Escolaridad: 'Secundaria completa' → aparece MÁS veces de lo esperado. Observado = 3,825; esperado = 1,764.86; 32.61% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Escolaridad: 'Sin escolaridad' → aparece MENOS veces de lo esperado. Observado = 316; esperado = 1,731.35; 2.69% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Escolaridad: 'Primaria incompleta' → aparece MENOS veces de lo esperado. Observado = 887; esperado = 2,508.04; 7.56% dentro de esta causa.

• Neumonia, no especificada — Escolaridad: 'No aplica a menores de 3' → aparece MÁS veces de lo esperado. Observado = 815; esperado = 304.39; 2.91% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Escolaridad: 'Bachillerato o preparatoria incompleto' → aparece MÁS veces de lo esperado. Observado = 797; esperado = 257.55; 6.79% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Escolaridad: 'Secundaria incompleta' → aparece MÁS veces de lo esperado. Observado = 945; esperado = 342.58; 8.06% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Escolaridad: 'Bachillerato o preparatoria completo' → aparece MÁS veces de lo esperado. Observado = 1,641; esperado = 910.75; 13.99% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Escolaridad: 'No aplica a menores de 3' → aparece MENOS veces de lo esperado. Observado = 1; esperado = 389.23; 0.00% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Escolaridad: 'Secundaria completa' → aparece MENOS veces de lo esperado. Observado = 4,159; esperado = 5,392.83; 11.60% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Escolaridad: 'Sin escolaridad' → aparece MÁS veces de lo esperado. Observado = 6,456; esperado = 5,290.43; 18.01% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Escolaridad: 'Primaria incompleta' → aparece MÁS veces de lo esperado. Observado = 8,957; esperado = 7,663.74; 24.99% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Escolaridad: 'Primaria completa' → aparece MÁS veces de lo esperado. Observado = 9,583; esperado = 8,387.21; 26.74% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Escolaridad: 'Secundaria incompleta' → aparece MENOS veces de lo esperado. Observado = 599; esperado = 1,046.80; 1.67% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Escolaridad: 'Bachillerato o preparatoria incompleto' → aparece MENOS veces de lo esperado. Observado = 401; esperado = 787.00; 1.12% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Escolaridad: 'Bachillerato o preparatoria completo' → aparece MENOS veces de lo esperado. Observado = 2,128; esperado = 2,782.94; 5.94% dentro de esta causa.

• Neumonia, no especificada — Escolaridad: 'Secundaria completa' → aparece MENOS veces de lo esperado. Observado = 3,391; esperado = 4,217.31; 12.10% dentro de esta causa.

• Neumonia, no especificada — Escolaridad: 'No especificado' → aparece MÁS veces de lo esperado. Observado = 1,127; esperado = 792.67; 4.02% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Escolaridad: 'Primaria completa' → aparece MENOS veces de lo esperado. Observado = 2,193; esperado = 2,744.80; 18.70% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Escolaridad: 'No aplica a menores de 3' → aparece MENOS veces de lo esperado. Observado = 5; esperado = 127.38; 0.04% dentro de esta causa.

• Neumonia, no especificada — Escolaridad: 'Primaria completa' → aparece MENOS veces de lo esperado. Observado = 5,915; esperado = 6,558.98; 21.10% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Escolaridad: 'No especificado' → aparece MENOS veces de lo esperado. Observado = 175; esperado = 331.72; 1.49% dentro de esta causa.

• Neumonia, no especificada — Escolaridad: 'Posgrado' → aparece MÁS veces de lo esperado. Observado = 240; esperado = 152.38; 0.86% dentro de esta causa.

• Neumonia, no especificada — Escolaridad: 'Profesional' → aparece MÁS veces de lo esperado. Observado = 2,537; esperado = 2,219.32; 9.05% dentro de esta causa.

• Neumonia, no especificada — Escolaridad: 'Bachillerato o preparatoria incompleto' → aparece MENOS veces de lo esperado. Observado = 462; esperado = 615.45; 1.65% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Escolaridad: 'No especificado' → aparece MENOS veces de lo esperado. Observado = 836; esperado = 1,013.61; 2.33% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Escolaridad: 'Profesional' → aparece MENOS veces de lo esperado. Observado = 2,567; esperado = 2,837.93; 7.16% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Escolaridad: 'Posgrado' → aparece MENOS veces de lo esperado. Observado = 124; esperado = 194.85; 0.35% dentro de esta causa.

• Neumonia, no especificada — Escolaridad: 'Secundaria incompleta' → aparece MENOS veces de lo esperado. Observado = 664; esperado = 818.62; 2.37% dentro de esta causa.

• Neumonia, no especificada — Escolaridad: 'Primaria incompleta' → aparece MÁS veces de lo esperado. Observado = 6,321; esperado = 5,993.21; 22.55% dentro de esta causa.

• Neumonia, no especificada — Escolaridad: 'Sin escolaridad' → aparece MÁS veces de lo esperado. Observado = 4,387; esperado = 4,137.23; 15.65% dentro de esta causa.

• Neumonia, no especificada — Escolaridad: 'Preescolar' → aparece MÁS veces de lo esperado. Observado = 70; esperado = 44.12; 0.25% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Escolaridad: 'Preescolar' → aparece MENOS veces de lo esperado. Observado = 32; esperado = 56.42; 0.09% dentro de esta causa.


####################################################################################################
CAUSA × Ocupacion_Ampliado
####################################################################################################

χ² = 17578.302
gl = 110
p = 0
V de Cramér = 0.341
Magnitud = Fuerte

Tabla de frecuencias observadas:

Ocupacion_Ampliado,Artesanos y trabajadores en el tratamiento y elaboración de productos de metal,"Artesanos y trabajadores en la elaboración de productos de cerámica, vidrio, azulejo y similares","Artesanos y trabajadores en la elaboración de productos de hule, caucho, plásticos y de sustancias químicas","Artesanos y trabajadores en la elaboración de productos de madera, papel, textiles y de cuero y piel","Auxiliares y técnicos en ciencias económico-administrativas, ciencias sociales, humanistas y en artes","Auxiliares y técnicos en ciencias exactas, biológicas, ingeniería, informática y en telecomunicaciones","Auxiliares y técnicos en educación, instructores y capacitadores","Ayudantes de conductores de transporte, conductores de transporte de tracción humana y animal y cargadores",Ayudantes en la preparación de alimentos,Busca trabajo,...,Trabajadores en actividades agrícolas y ganaderas,"Trabajadores en actividades pesqueras, forestales, caza y similares",Trabajadores en cuidados personales y del hogar,"Trabajadores en la elaboración y procesamiento de alimentos, bebidas y productos de tabaco",Trabajadores en la extracción y la edificación de construcciones,"Trabajadores en la preparación y servicio de alimentos y bebidas, así como en servicios de esparcimiento y de hotelería",Trabajadores en servicios de alquiler,Trabajadores en servicios de protección y vigilancia,Vendedores ambulantes,TOTAL
"Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras",198,20,21,84,29,375,2,45,9,0,...,924,35,108,66,1097,86,3,310,16,11730
"Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas",217,16,9,271,50,335,6,12,4,1,...,3290,67,69,101,800,88,2,244,21,35843
"Neumonia, no especificada",166,24,6,192,49,284,12,13,3,1,...,2144,55,77,63,632,106,2,260,20,28030
TOTAL,581,60,36,547,128,994,20,70,16,2,...,6358,157,254,230,2529,280,7,814,57,75603

Categorías específicamente asociadas:

Interpretación de las categorías:

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'No trabaja' → aparece MENOS veces de lo esperado. Observado = 1,689; esperado = 6,459.47; 14.40% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Ocupaciones insuficientemente especificadas' → aparece MÁS veces de lo esperado. Observado = 1,876; esperado = 544.74; 15.99% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'No trabaja' → aparece MÁS veces de lo esperado. Observado = 22,987; esperado = 19,737.99; 64.13% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Trabajadores en la extracción y la edificación de construcciones' → aparece MÁS veces de lo esperado. Observado = 1,097; esperado = 392.38; 9.35% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'No aplica a menores de 5 años' → aparece MÁS veces de lo esperado. Observado = 905; esperado = 338.13; 3.23% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Conductores de transporte y de maquinaria móvil' → aparece MÁS veces de lo esperado. Observado = 932; esperado = 349.40; 7.95% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'No aplica a menores de 5 años' → aparece MENOS veces de lo esperado. Observado = 1; esperado = 432.37; 0.00% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Trabajadores de apoyo en actividades agropecuarias, forestales, pesca y caza' → aparece MÁS veces de lo esperado. Observado = 412; esperado = 122.42; 3.51% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Trabajadores de apoyo en la minería, construcción e industria' → aparece MÁS veces de lo esperado. Observado = 256; esperado = 57.41; 2.18% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Comerciantes en establecimientos' → aparece MÁS veces de lo esperado. Observado = 1,422; esperado = 744.89; 12.12% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Ocupaciones insuficientemente especificadas' → aparece MENOS veces de lo esperado. Observado = 912; esperado = 1,664.55; 2.54% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'No trabaja' → aparece MÁS veces de lo esperado. Observado = 16,957; esperado = 15,435.54; 60.50% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'Ocupaciones insuficientemente especificadas' → aparece MENOS veces de lo esperado. Observado = 723; esperado = 1,301.71; 2.58% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Auxiliares y técnicos en ciencias exactas, biológicas, ingeniería, informática y en telecomunicaciones' → aparece MÁS veces de lo esperado. Observado = 375; esperado = 154.22; 3.20% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Trabajadores en servicios de protección y vigilancia' → aparece MÁS veces de lo esperado. Observado = 310; esperado = 126.29; 2.64% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Trabajadores en la extracción y la edificación de construcciones' → aparece MENOS veces de lo esperado. Observado = 800; esperado = 1,198.99; 2.23% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Trabajadores de paquetería, de apoyo para espectáculos, mensajeros y repartidores de mercancías' → aparece MÁS veces de lo esperado. Observado = 70; esperado = 15.36; 0.60% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'Comerciantes en establecimientos' → aparece MENOS veces de lo esperado. Observado = 1,295; esperado = 1,779.98; 4.62% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'Conductores de transporte y de maquinaria móvil' → aparece MENOS veces de lo esperado. Observado = 503; esperado = 834.93; 1.79% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Trabajadores de apoyo en la minería, construcción e industria' → aparece MENOS veces de lo esperado. Observado = 42; esperado = 175.42; 0.12% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Trabajadores domésticos, de limpieza, planchadores y otros trabajadores de limpieza' → aparece MÁS veces de lo esperado. Observado = 191; esperado = 78.51; 1.63% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'Trabajadores en la extracción y la edificación de construcciones' → aparece MENOS veces de lo esperado. Observado = 632; esperado = 937.63; 2.25% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'No aplica a menores de 5 años' → aparece MENOS veces de lo esperado. Observado = 6; esperado = 141.50; 0.05% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Artesanos y trabajadores en el tratamiento y elaboración de productos de metal' → aparece MÁS veces de lo esperado. Observado = 198; esperado = 90.14; 1.69% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Otros trabajadores artesanales no clasificados anteriormente' → aparece MÁS veces de lo esperado. Observado = 389; esperado = 222.18; 3.32% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'No especificada' → aparece MÁS veces de lo esperado. Observado = 1,293; esperado = 992.88; 4.61% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Trabajadores en cuidados personales y del hogar' → aparece MÁS veces de lo esperado. Observado = 108; esperado = 39.41; 0.92% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Ayudantes de conductores de transporte, conductores de transporte de tracción humana y animal y cargadores' → aparece MÁS veces de lo esperado. Observado = 45; esperado = 10.86; 0.38% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Otros trabajadores en actividades elementales y de apoyo, no clasificados anteriormente' → aparece MÁS veces de lo esperado. Observado = 40; esperado = 9.00; 0.34% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Otros trabajadores auxiliares en actividades administrativas, no clasificados anteriormente' → aparece MÁS veces de lo esperado. Observado = 95; esperado = 34.91; 0.81% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Empleados de ventas en establecimientos' → aparece MÁS veces de lo esperado. Observado = 94; esperado = 35.22; 0.80% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'Trabajadores de apoyo en actividades agropecuarias, forestales, pesca y caza' → aparece MENOS veces de lo esperado. Observado = 147; esperado = 292.52; 0.52% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Conductores de transporte y de maquinaria móvil' → aparece MENOS veces de lo esperado. Observado = 817; esperado = 1,067.66; 2.28% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Trabajadores domésticos, de limpieza, planchadores y otros trabajadores de limpieza' → aparece MENOS veces de lo esperado. Observado = 122; esperado = 239.89; 0.34% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Trabajadores de apoyo en actividades agropecuarias, forestales, pesca y caza' → aparece MENOS veces de lo esperado. Observado = 230; esperado = 374.06; 0.64% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Trabajadores de la Armada, Ejército y Fuerza Aérea' → aparece MÁS veces de lo esperado. Observado = 33; esperado = 7.60; 0.28% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Trabajadores en servicios de protección y vigilancia' → aparece MENOS veces de lo esperado. Observado = 244; esperado = 385.91; 0.68% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'No especificada' → aparece MENOS veces de lo esperado. Observado = 236; esperado = 415.50; 2.01% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Auxiliares y técnicos en ciencias exactas, biológicas, ingeniería, informática y en telecomunicaciones' → aparece MENOS veces de lo esperado. Observado = 335; esperado = 471.25; 0.93% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Otros directores, funcionarios, gerentes, coordinadores y jefes de área, no clasificados anteriormente' → aparece MÁS veces de lo esperado. Observado = 83; esperado = 36.93; 0.71% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Trabajadores de paquetería, de apoyo para espectáculos, mensajeros y repartidores de mercancías' → aparece MENOS veces de lo esperado. Observado = 9; esperado = 46.94; 0.03% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Trabajadores en actividades agrícolas y ganaderas' → aparece MÁS veces de lo esperado. Observado = 3,290; esperado = 3,014.30; 9.18% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Empleados de ventas en establecimientos' → aparece MENOS veces de lo esperado. Observado = 54; esperado = 107.62; 0.15% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Artesanos y trabajadores en la elaboración de productos de hule, caucho, plásticos y de sustancias químicas' → aparece MÁS veces de lo esperado. Observado = 21; esperado = 5.59; 0.18% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Trabajadores en la preparación y servicio de alimentos y bebidas, así como en servicios de esparcimiento y de hotelería' → aparece MÁS veces de lo esperado. Observado = 86; esperado = 43.44; 0.73% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'Trabajadores de apoyo en la minería, construcción e industria' → aparece MENOS veces de lo esperado. Observado = 72; esperado = 137.18; 0.26% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Otros trabajadores en actividades elementales y de apoyo, no clasificados anteriormente' → aparece MENOS veces de lo esperado. Observado = 1; esperado = 27.50; 0.00% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Otros trabajadores auxiliares en actividades administrativas, no clasificados anteriormente' → aparece MENOS veces de lo esperado. Observado = 56; esperado = 106.67; 0.16% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Trabajadores en cuidados personales y del hogar' → aparece MENOS veces de lo esperado. Observado = 69; esperado = 120.42; 0.19% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'Otros trabajadores artesanales no clasificados anteriormente' → aparece MENOS veces de lo esperado. Observado = 418; esperado = 530.92; 1.49% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Otros directores, funcionarios, gerentes, coordinadores y jefes de área, no clasificados anteriormente' → aparece MENOS veces de lo esperado. Observado = 67; esperado = 112.83; 0.19% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'Trabajadores en actividades agrícolas y ganaderas' → aparece MENOS veces de lo esperado. Observado = 2,144; esperado = 2,357.24; 7.65% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Comerciantes en establecimientos' → aparece MENOS veces de lo esperado. Observado = 2,084; esperado = 2,276.13; 5.81% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'Auxiliares y técnicos en ciencias exactas, biológicas, ingeniería, informática y en telecomunicaciones' → aparece MENOS veces de lo esperado. Observado = 284; esperado = 368.53; 1.01% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Trabajadores en la elaboración y procesamiento de alimentos, bebidas y productos de tabaco' → aparece MÁS veces de lo esperado. Observado = 66; esperado = 35.69; 0.56% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Trabajadores en la preparación y servicio de alimentos y bebidas, así como en servicios de esparcimiento y de hotelería' → aparece MENOS veces de lo esperado. Observado = 88; esperado = 132.75; 0.25% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Ayudantes de conductores de transporte, conductores de transporte de tracción humana y animal y cargadores' → aparece MENOS veces de lo esperado. Observado = 12; esperado = 33.19; 0.03% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Funcionarios y altas autoridades de los sectores público, privado y social' → aparece MÁS veces de lo esperado. Observado = 12; esperado = 3.41; 0.10% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Otros operadores de maquinaria industrial, ensambladores y conductores de transporte, no clasificados anteriormente' → aparece MÁS veces de lo esperado. Observado = 47; esperado = 24.51; 0.40% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Supervisores de personal de apoyo administrativo, secretarias, capturistas, cajeros y trabajadores de control de archivo y transporte' → aparece MENOS veces de lo esperado. Observado = 88; esperado = 128.48; 0.25% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Artesanos y trabajadores en el tratamiento y elaboración de productos de metal' → aparece MENOS veces de lo esperado. Observado = 217; esperado = 275.45; 0.61% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'No especificada' → aparece MENOS veces de lo esperado. Observado = 1,149; esperado = 1,269.63; 3.21% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Trabajadores de la Armada, Ejército y Fuerza Aérea' → aparece MENOS veces de lo esperado. Observado = 7; esperado = 23.23; 0.02% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Ayudantes en la preparación de alimentos' → aparece MÁS veces de lo esperado. Observado = 9; esperado = 2.48; 0.08% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'Artesanos y trabajadores en el tratamiento y elaboración de productos de metal' → aparece MENOS veces de lo esperado. Observado = 166; esperado = 215.41; 0.59% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Operadores de instalaciones y maquinaria industrial' → aparece MÁS veces de lo esperado. Observado = 27; esperado = 13.19; 0.23% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'Supervisores de personal de apoyo administrativo, secretarias, capturistas, cajeros y trabajadores de control de archivo y transporte' → aparece MÁS veces de lo esperado. Observado = 133; esperado = 100.47; 0.47% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Otros comerciantes, empleados en ventas y agentes de ventas en establecimientos, no clasificados anteriormente' → aparece MENOS veces de lo esperado. Observado = 11; esperado = 26.08; 0.03% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Profesores y especialistas en docencia' → aparece MENOS veces de lo esperado. Observado = 56; esperado = 90.61; 0.48% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Profesionistas en ciencias económico-administrativas, ciencias sociales, humanistas y en artes' → aparece MENOS veces de lo esperado. Observado = 250; esperado = 297.73; 0.70% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Artesanos y trabajadores en la elaboración de productos de cerámica, vidrio, azulejo y similares' → aparece MÁS veces de lo esperado. Observado = 20; esperado = 9.31; 0.17% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion_Ampliado: 'Supervisores y trabajadores que brindan y manejan información' → aparece MENOS veces de lo esperado. Observado = 9; esperado = 20.86; 0.03% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Directores y gerentes en servicios financieros, legales, administrativos y sociales' → aparece MÁS veces de lo esperado. Observado = 6; esperado = 1.71; 0.05% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion_Ampliado: 'Coordinadores y jefes de área en servicios financieros, administrativos y sociales' → aparece MÁS veces de lo esperado. Observado = 7; esperado = 2.17; 0.06% dentro de esta causa.

• Neumonia, no especificada — Ocupacion_Ampliado: 'Trabajadores de paquetería, de apoyo para espectáculos, mensajeros y repartidores de mercancías' → aparece MENOS veces de lo esperado. Observado = 20; esperado = 36.70; 0.07% dentro de esta causa.


####################################################################################################
CAUSA × Ocupacion

Ocupacion,Administrativos,Agropecuario y pesca,Comercio y ventas,Construcción y manufactura,Dirección y gerencia,Fuerzas armadas,No especificado / fuera de clasificación,Operadores y transporte,Profesionistas,Servicios,Trabajo elemental y apoyo,Técnicos y auxiliares,TOTAL
"Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras",154,964,1536,1875,115,33,3807,1008,225,504,1039,470,11730
"Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas",153,3363,2151,2039,86,7,25050,904,715,401,441,533,35843
"Neumonia, no especificada",233,2207,1403,1501,114,9,19879,586,700,443,485,470,28030
TOTAL,540,6534,5090,5415,315,49,48736,2498,1640,1348,1965,1473,75603

Categorías específicamente asociadas:

Interpretación de las categorías:

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion: 'No especificado / fuera de clasificación' → aparece MENOS veces de lo esperado. Observado = 3,807; esperado = 7,561.52; 32.46% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion: 'Trabajo elemental y apoyo' → aparece MÁS veces de lo esperado. Observado = 1,039; esperado = 304.87; 8.86% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion: 'Construcción y manufactura' → aparece MÁS veces de lo esperado. Observado = 1,875; esperado = 840.15; 15.98% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion: 'Operadores y transporte' → aparece MÁS veces de lo esperado. Observado = 1,008; esperado = 387.57; 8.59% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion: 'Comercio y ventas' → aparece MÁS veces de lo esperado. Observado = 1,536; esperado = 789.73; 13.09% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion: 'No especificado / fuera de clasificación' → aparece MÁS veces de lo esperado. Observado = 25,050; esperado = 23,105.49; 69.89% dentro de esta causa.

• Neumonia, no especificada — Ocupacion: 'No especificado / fuera de clasificación' → aparece MÁS veces de lo esperado. Observado = 19,879; esperado = 18,068.99; 70.92% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion: 'Trabajo elemental y apoyo' → aparece MENOS veces de lo esperado. Observado = 441; esperado = 931.60; 1.23% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion: 'Servicios' → aparece MÁS veces de lo esperado. Observado = 504; esperado = 209.15; 4.30% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion: 'Técnicos y auxiliares' → aparece MÁS veces de lo esperado. Observado = 470; esperado = 228.54; 4.01% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion: 'Construcción y manufactura' → aparece MENOS veces de lo esperado. Observado = 2,039; esperado = 2,567.22; 5.69% dentro de esta causa.

• Neumonia, no especificada — Ocupacion: 'Construcción y manufactura' → aparece MENOS veces de lo esperado. Observado = 1,501; esperado = 2,007.62; 5.35% dentro de esta causa.

• Neumonia, no especificada — Ocupacion: 'Comercio y ventas' → aparece MENOS veces de lo esperado. Observado = 1,403; esperado = 1,887.13; 5.01% dentro de esta causa.

• Neumonia, no especificada — Ocupacion: 'Operadores y transporte' → aparece MENOS veces de lo esperado. Observado = 586; esperado = 926.14; 2.09% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion: 'Servicios' → aparece MENOS veces de lo esperado. Observado = 401; esperado = 639.08; 1.12% dentro de esta causa.

• Neumonia, no especificada — Ocupacion: 'Trabajo elemental y apoyo' → aparece MENOS veces de lo esperado. Observado = 485; esperado = 728.53; 1.73% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion: 'Operadores y transporte' → aparece MENOS veces de lo esperado. Observado = 904; esperado = 1,184.29; 2.52% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion: 'Dirección y gerencia' → aparece MÁS veces de lo esperado. Observado = 115; esperado = 48.87; 0.98% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion: 'Fuerzas armadas' → aparece MÁS veces de lo esperado. Observado = 33; esperado = 7.60; 0.28% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion: 'Administrativos' → aparece MENOS veces de lo esperado. Observado = 153; esperado = 256.01; 0.43% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion: 'Técnicos y auxiliares' → aparece MENOS veces de lo esperado. Observado = 533; esperado = 698.34; 1.49% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — Ocupacion: 'Administrativos' → aparece MÁS veces de lo esperado. Observado = 154; esperado = 83.78; 1.31% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion: 'Comercio y ventas' → aparece MENOS veces de lo esperado. Observado = 2,151; esperado = 2,413.14; 6.00% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion: 'Dirección y gerencia' → aparece MENOS veces de lo esperado. Observado = 86; esperado = 149.34; 0.24% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion: 'Agropecuario y pesca' → aparece MÁS veces de lo esperado. Observado = 3,363; esperado = 3,097.74; 9.38% dentro de esta causa.

• Neumonia, no especificada — Ocupacion: 'Agropecuario y pesca' → aparece MENOS veces de lo esperado. Observado = 2,207; esperado = 2,422.50; 7.87% dentro de esta causa.

• Neumonia, no especificada — Ocupacion: 'Profesionistas' → aparece MÁS veces de lo esperado. Observado = 700; esperado = 608.03; 2.50% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion: 'Fuerzas armadas' → aparece MENOS veces de lo esperado. Observado = 7; esperado = 23.23; 0.02% dentro de esta causa.

• Neumonia, no especificada — Ocupacion: 'Técnicos y auxiliares' → aparece MENOS veces de lo esperado. Observado = 470; esperado = 546.12; 1.68% dentro de esta causa.

• Neumonia, no especificada — Ocupacion: 'Servicios' → aparece MENOS veces de lo esperado. Observado = 443; esperado = 499.77; 1.58% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — Ocupacion: 'Profesionistas' → aparece MENOS veces de lo esperado. Observado = 715; esperado = 777.52; 1.99% dentro de esta causa.

• Neumonia, no especificada — Ocupacion: 'Administrativos' → aparece MÁS veces de lo esperado. Observado = 233; esperado = 200.21; 0.83% dentro de esta causa.

• Neumonia, no especificada — Ocupacion: 'Fuerzas armadas' → aparece MENOS veces de lo esperado. Observado = 9; esperado = 18.17; 0.03% dentro de esta causa.


####################################################################################################
CAUSA × EstadoCivil
####################################################################################################

χ² = 11378.856
gl = 14
p = 0
V de Cramér = 0.274
Magnitud = Moderada

Tabla de frecuencias observadas:

EstadoCivil,Casado(a),Divorciado(a),No aplica a menores de 12,No especificado,Separado(a),Soltero(a),Union Libre,Viudo(a),TOTAL
"Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras",2171,208,31,559,159,5702,2798,102,11730
"Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas",13331,740,1,1736,481,7501,2552,9501,35843
"Neumonia, no especificada",9408,694,1018,1388,373,5960,1886,7303,28030
TOTAL,24910,1642,1050,3683,1013,19163,7236,16906,75603

Categorías específicamente asociadas:

Interpretación de las categorías:

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — EstadoCivil: 'Soltero(a)' → aparece MÁS veces de lo esperado. Observado = 5,702; esperado = 2,973.19; 48.61% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — EstadoCivil: 'Viudo(a)' → aparece MENOS veces de lo esperado. Observado = 102; esperado = 2,623.01; 0.87% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — EstadoCivil: 'Union Libre' → aparece MÁS veces de lo esperado. Observado = 2,798; esperado = 1,122.68; 23.85% dentro de esta causa.

• Neumonia, no especificada — EstadoCivil: 'No aplica a menores de 12' → aparece MÁS veces de lo esperado. Observado = 1,018; esperado = 389.29; 3.63% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — EstadoCivil: 'Casado(a)' → aparece MENOS veces de lo esperado. Observado = 2,171; esperado = 3,864.85; 18.51% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — EstadoCivil: 'No aplica a menores de 12' → aparece MENOS veces de lo esperado. Observado = 1; esperado = 497.80; 0.00% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — EstadoCivil: 'Soltero(a)' → aparece MENOS veces de lo esperado. Observado = 7,501; esperado = 9,085.08; 20.93% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — EstadoCivil: 'Viudo(a)' → aparece MÁS veces de lo esperado. Observado = 9,501; esperado = 8,015.05; 26.51% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — EstadoCivil: 'Casado(a)' → aparece MÁS veces de lo esperado. Observado = 13,331; esperado = 11,809.71; 37.19% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — EstadoCivil: 'Union Libre' → aparece MENOS veces de lo esperado. Observado = 2,552; esperado = 3,430.55; 7.12% dentro de esta causa.

• Neumonia, no especificada — EstadoCivil: 'Union Libre' → aparece MENOS veces de lo esperado. Observado = 1,886; esperado = 2,682.76; 6.73% dentro de esta causa.

• Neumonia, no especificada — EstadoCivil: 'Soltero(a)' → aparece MENOS veces de lo esperado. Observado = 5,960; esperado = 7,104.73; 21.26% dentro de esta causa.

• Neumonia, no especificada — EstadoCivil: 'Viudo(a)' → aparece MÁS veces de lo esperado. Observado = 7,303; esperado = 6,267.94; 26.05% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — EstadoCivil: 'No aplica a menores de 12' → aparece MENOS veces de lo esperado. Observado = 31; esperado = 162.91; 0.26% dentro de esta causa.

• Neumonia, no especificada — EstadoCivil: 'Divorciado(a)' → aparece MÁS veces de lo esperado. Observado = 694; esperado = 608.78; 2.48% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — EstadoCivil: 'Divorciado(a)' → aparece MENOS veces de lo esperado. Observado = 208; esperado = 254.76; 1.77% dentro de esta causa.

• Neumonia, no especificada — EstadoCivil: 'Casado(a)' → aparece MÁS veces de lo esperado. Observado = 9,408; esperado = 9,235.44; 33.56% dentro de esta causa.


####################################################################################################
CAUSA × CondicionIndigena
####################################################################################################

χ² = 969.957
gl = 6
p = 2.80941e-206
V de Cramér = 0.080
Magnitud = Muy débil

Tabla de frecuencias observadas:

CondicionIndigena,No,No aplica,No especificado,Si,TOTAL
"Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras",9544,725,1172,289,11730
"Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas",29786,2454,1464,2139,35843
"Neumonia, no especificada",23640,1373,1283,1734,28030
TOTAL,62970,4552,3919,4162,75603

Categorías específicamente asociadas:

Interpretación de las categorías:

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — CondicionIndigena: 'No especificado' → aparece MÁS veces de lo esperado. Observado = 1,172; esperado = 608.04; 9.99% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — CondicionIndigena: 'Si' → aparece MENOS veces de lo esperado. Observado = 289; esperado = 645.75; 2.46% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — CondicionIndigena: 'No especificado' → aparece MENOS veces de lo esperado. Observado = 1,464; esperado = 1,857.98; 4.08% dentro de esta causa.

• Neumonia, no especificada — CondicionIndigena: 'No aplica' → aparece MENOS veces de lo esperado. Observado = 1,373; esperado = 1,687.67; 4.90% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — CondicionIndigena: 'No aplica' → aparece MÁS veces de lo esperado. Observado = 2,454; esperado = 2,158.08; 6.85% dentro de esta causa.

• Neumonia, no especificada — CondicionIndigena: 'Si' → aparece MÁS veces de lo esperado. Observado = 1,734; esperado = 1,543.07; 6.19% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — CondicionIndigena: 'No' → aparece MENOS veces de lo esperado. Observado = 9,544; esperado = 9,769.96; 81.36% dentro de esta causa.

• Neumonia, no especificada — CondicionIndigena: 'No' → aparece MÁS veces de lo esperado. Observado = 23,640; esperado = 23,346.28; 84.34% dentro de esta causa.

• Neumonia, no especificada — CondicionIndigena: 'No especificado' → aparece MENOS veces de lo esperado. Observado = 1,283; esperado = 1,452.98; 4.58% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — CondicionIndigena: 'Si' → aparece MÁS veces de lo esperado. Observado = 2,139; esperado = 1,973.18; 5.97% dentro de esta causa.


####################################################################################################
CAUSA × AfroMexicanos
####################################################################################################

χ² = 387.380
gl = 6
p = 1.44244e-80
V de Cramér = 0.051
Magnitud = Muy débil

Tabla de frecuencias observadas:

AfroMexicanos,No,No aplica,No especificado,Si,TOTAL
"Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras",10046,725,902,57,11730
"Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas",31635,2454,1508,246,35843
"Neumonia, no especificada",25307,1373,1156,194,28030
TOTAL,66988,4552,3566,497,75603

Categorías específicamente asociadas:

Interpretación de las categorías:

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — AfroMexicanos: 'No especificado' → aparece MÁS veces de lo esperado. Observado = 902; esperado = 553.27; 7.69% dentro de esta causa.

• Neumonia, no especificada — AfroMexicanos: 'No' → aparece MÁS veces de lo esperado. Observado = 25,307; esperado = 24,835.97; 90.29% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — AfroMexicanos: 'No' → aparece MENOS veces de lo esperado. Observado = 10,046; esperado = 10,393.36; 85.64% dentro de esta causa.

• Neumonia, no especificada — AfroMexicanos: 'No aplica' → aparece MENOS veces de lo esperado. Observado = 1,373; esperado = 1,687.67; 4.90% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — AfroMexicanos: 'No aplica' → aparece MÁS veces de lo esperado. Observado = 2,454; esperado = 2,158.08; 6.85% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — AfroMexicanos: 'No especificado' → aparece MENOS veces de lo esperado. Observado = 1,508; esperado = 1,690.62; 4.21% dentro de esta causa.

• Neumonia, no especificada — AfroMexicanos: 'No especificado' → aparece MENOS veces de lo esperado. Observado = 1,156; esperado = 1,322.10; 4.12% dentro de esta causa.

• Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas — AfroMexicanos: 'No' → aparece MENOS veces de lo esperado. Observado = 31,635; esperado = 31,758.67; 88.26% dentro de esta causa.

• Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras — AfroMexicanos: 'Si' → aparece MENOS veces de lo esperado. Observado = 57; esperado = 77.11; 0.49% dentro de esta causa.


====================================================================================================
3. RESUMEN: CATEGORÍAS ASOCIADAS A CADA CAUSA
====================================================================================================


----------------------------------------------------------------------------------------------------
CAUSA: Neumonia, no especificada
----------------------------------------------------------------------------------------------------

Sexo:
   ↑ Mujer | observado: 12,670 | esperado: 11,616.05 | residual: 16.11
   ↓ Hombre | observado: 15,360 | esperado: 16,413.95 | residual: -16.11

AfroMexicanos:
   ↑ No | observado: 25,307 | esperado: 24,835.97 | residual: 11.16
   ↓ No especificado | observado: 1,156 | esperado: 1,322.10 | residual: -5.90
   ↓ No aplica | observado: 1,373 | esperado: 1,687.67 | residual: -9.96

CondicionIndigena:
   ↑ Si | observado: 1,734 | esperado: 1,543.07 | residual: 6.30
   ↑ No | observado: 23,640 | esperado: 23,346.28 | residual: 5.93
   ↓ No especificado | observado: 1,283 | esperado: 1,452.98 | residual: -5.77
   ↓ No aplica | observado: 1,373 | esperado: 1,687.67 | residual: -9.96

Escolaridad:
   ↑ No aplica a menores de 3 | observado: 815 | esperado: 304.39 | residual: 37.10
   ↑ No especificado | observado: 1,127 | esperado: 792.67 | residual: 15.19
   ↑ Posgrado | observado: 240 | esperado: 152.38 | residual: 8.97
   ↑ Profesional | observado: 2,537 | esperado: 2,219.32 | residual: 8.86
   ↑ Primaria incompleta | observado: 6,321 | esperado: 5,993.21 | residual: 6.02
   ↑ Sin escolaridad | observado: 4,387 | esperado: 4,137.23 | residual: 5.30
   ↑ Preescolar | observado: 70 | esperado: 44.12 | residual: 4.92
   ↓ Secundaria incompleta | observado: 664 | esperado: 818.62 | residual: -6.91
   ↓ Bachillerato o preparatoria incompleto | observado: 462 | esperado: 615.45 | residual: -7.88
   ↓ Primaria completa | observado: 5,915 | esperado: 6,558.98 | residual: -11.45
   ↓ Secundaria completa | observado: 3,391 | esperado: 4,217.31 | residual: -17.40

Ocupacion:
   ↑ No especificado / fuera de clasificación | observado: 19,879 | esperado: 18,068.99 | residual: 28.47
   ↑ Profesionistas | observado: 700 | esperado: 608.03 | residual: 4.75
   ↑ Administrativos | observado: 233 | esperado: 200.21 | residual: 2.93
   ↓ Fuerzas armadas | observado: 9 | esperado: 18.17 | residual: -2.71
   ↓ Servicios | observado: 443 | esperado: 499.77 | residual: -3.23
   ↓ Técnicos y auxiliares | observado: 470 | esperado: 546.12 | residual: -4.15
   ↓ Agropecuario y pesca | observado: 2,207 | esperado: 2,422.50 | residual: -5.77
   ↓ Trabajo elemental y apoyo | observado: 485 | esperado: 728.53 | residual: -11.52
   ↓ Operadores y transporte | observado: 586 | esperado: 926.14 | residual: -14.33
   ↓ Comercio y ventas | observado: 1,403 | esperado: 1,887.13 | residual: -14.55
   ↓ Construcción y manufactura | observado: 1,501 | esperado: 2,007.62 | residual: -14.79

Ocupacion_Ampliado:
   ↑ No aplica a menores de 5 años | observado: 905 | esperado: 338.13 | residual: 39.10
   ↑ No trabaja | observado: 16,957 | esperado: 15,435.54 | residual: 23.03
   ↑ No especificada | observado: 1,293 | esperado: 992.88 | residual: 12.23
   ↑ Supervisores de personal de apoyo administrativo, secretarias, capturistas, cajeros y trabajadores de control de archivo y transporte | observado: 133 | esperado: 100.47 | residual: 4.10
   ↓ Trabajadores de paquetería, de apoyo para espectáculos, mensajeros y repartidores de mercancías | observado: 20 | esperado: 36.70 | residual: -3.48
   ↓ Artesanos y trabajadores en el tratamiento y elaboración de productos de metal | observado: 166 | esperado: 215.41 | residual: -4.26
   ↓ Auxiliares y técnicos en ciencias exactas, biológicas, ingeniería, informática y en telecomunicaciones | observado: 284 | esperado: 368.53 | residual: -5.59
   ↓ Trabajadores en actividades agrícolas y ganaderas | observado: 2,144 | esperado: 2,357.24 | residual: -5.79
   ↓ Otros trabajadores artesanales no clasificados anteriormente | observado: 418 | esperado: 530.92 | residual: -6.24
   ↓ Trabajadores de apoyo en la minería, construcción e industria | observado: 72 | esperado: 137.18 | residual: -7.03
   ↓ Trabajadores de apoyo en actividades agropecuarias, forestales, pesca y caza | observado: 147 | esperado: 292.52 | residual: -10.78
   ↓ Trabajadores en la extracción y la edificación de construcciones | observado: 632 | esperado: 937.63 | residual: -12.80
   ↓ Conductores de transporte y de maquinaria móvil | observado: 503 | esperado: 834.93 | residual: -14.70
   ↓ Comerciantes en establecimientos | observado: 1,295 | esperado: 1,779.98 | residual: -14.97
   ↓ Ocupaciones insuficientemente especificadas | observado: 723 | esperado: 1,301.71 | residual: -20.71

EstadoCivil:
   ↑ No aplica a menores de 12 | observado: 1,018 | esperado: 389.29 | residual: 40.45
   ↑ Viudo(a) | observado: 7,303 | esperado: 6,267.94 | residual: 18.70
   ↑ Divorciado(a) | observado: 694 | esperado: 608.78 | residual: 4.40
   ↑ Casado(a) | observado: 9,408 | esperado: 9,235.44 | residual: 2.76
   ↓ Soltero(a) | observado: 5,960 | esperado: 7,104.73 | residual: -19.82
   ↓ Union Libre | observado: 1,886 | esperado: 2,682.76 | residual: -20.39


----------------------------------------------------------------------------------------------------
CAUSA: Diabetes Mellitus Tipo 2, Con Otras Complicaciones Especificadas
----------------------------------------------------------------------------------------------------

Sexo:
   ↑ Mujer | observado: 17,722 | esperado: 14,853.87 | residual: 42.41
   ↓ Hombre | observado: 18,121 | esperado: 20,989.13 | residual: -42.41

AfroMexicanos:
   ↑ No aplica | observado: 2,454 | esperado: 2,158.08 | residual: 9.06
   ↓ No | observado: 31,635 | esperado: 31,758.67 | residual: -2.83
   ↓ No especificado | observado: 1,508 | esperado: 1,690.62 | residual: -6.27

CondicionIndigena:
   ↑ No aplica | observado: 2,454 | esperado: 2,158.08 | residual: 9.06
   ↑ Si | observado: 2,139 | esperado: 1,973.18 | residual: 5.30
   ↓ No especificado | observado: 1,464 | esperado: 1,857.98 | residual: -12.94

Escolaridad:
   ↑ Sin escolaridad | observado: 6,456 | esperado: 5,290.43 | residual: 23.93
   ↑ Primaria incompleta | observado: 8,957 | esperado: 7,663.74 | residual: 22.97
   ↑ Primaria completa | observado: 9,583 | esperado: 8,387.21 | residual: 20.57
   ↓ Preescolar | observado: 32 | esperado: 56.42 | residual: -4.49
   ↓ Posgrado | observado: 124 | esperado: 194.85 | residual: -7.02
   ↓ Profesional | observado: 2,567 | esperado: 2,837.93 | residual: -7.31
   ↓ No especificado | observado: 836 | esperado: 1,013.61 | residual: -7.80
   ↓ Bachillerato o preparatoria completo | observado: 2,128 | esperado: 2,782.94 | residual: -17.83
   ↓ Bachillerato o preparatoria incompleto | observado: 401 | esperado: 787.00 | residual: -19.19
   ↓ Secundaria incompleta | observado: 599 | esperado: 1,046.80 | residual: -19.37
   ↓ Secundaria completa | observado: 4,159 | esperado: 5,392.83 | residual: -25.14
   ↓ No aplica a menores de 3 | observado: 1 | esperado: 389.23 | residual: -27.28

Ocupacion:
   ↑ No especificado / fuera de clasificación | observado: 25,050 | esperado: 23,105.49 | residual: 29.59
   ↑ Agropecuario y pesca | observado: 3,363 | esperado: 3,097.74 | residual: 6.88
   ↓ Profesionistas | observado: 715 | esperado: 777.52 | residual: -3.13
   ↓ Fuerzas armadas | observado: 7 | esperado: 23.23 | residual: -4.65
   ↓ Dirección y gerencia | observado: 86 | esperado: 149.34 | residual: -7.16
   ↓ Comercio y ventas | observado: 2,151 | esperado: 2,413.14 | residual: -7.62
   ↓ Técnicos y auxiliares | observado: 533 | esperado: 698.34 | residual: -8.71
   ↓ Administrativos | observado: 153 | esperado: 256.01 | residual: -8.91
   ↓ Operadores y transporte | observado: 904 | esperado: 1,184.29 | residual: -11.42
   ↓ Servicios | observado: 401 | esperado: 639.08 | residual: -13.10
   ↓ Construcción y manufactura | observado: 2,039 | esperado: 2,567.22 | residual: -14.92
   ↓ Trabajo elemental y apoyo | observado: 441 | esperado: 931.60 | residual: -22.46

Ocupacion_Ampliado:
   ↑ No trabaja | observado: 22,987 | esperado: 19,737.99 | residual: 47.57
   ↑ Trabajadores en actividades agrícolas y ganaderas | observado: 3,290 | esperado: 3,014.30 | residual: 7.24
   ↓ Supervisores y trabajadores que brindan y manejan información | observado: 9 | esperado: 20.86 | residual: -3.58
   ↓ Profesionistas en ciencias económico-administrativas, ciencias sociales, humanistas y en artes | observado: 250 | esperado: 297.73 | residual: -3.83
   ↓ Otros comerciantes, empleados en ventas y agentes de ventas en establecimientos, no clasificados anteriormente | observado: 11 | esperado: 26.08 | residual: -4.07
   ↓ Trabajadores de la Armada, Ejército y Fuerza Aérea | observado: 7 | esperado: 23.23 | residual: -4.65
   ↓ No especificada | observado: 1,149 | esperado: 1,269.63 | residual: -4.75
   ↓ Artesanos y trabajadores en el tratamiento y elaboración de productos de metal | observado: 217 | esperado: 275.45 | residual: -4.88
   ↓ Supervisores de personal de apoyo administrativo, secretarias, capturistas, cajeros y trabajadores de control de archivo y transporte | observado: 88 | esperado: 128.48 | residual: -4.93
   ↓ Ayudantes de conductores de transporte, conductores de transporte de tracción humana y animal y cargadores | observado: 12 | esperado: 33.19 | residual: -5.07
   ↓ Trabajadores en la preparación y servicio de alimentos y bebidas, así como en servicios de esparcimiento y de hotelería | observado: 88 | esperado: 132.75 | residual: -5.37
   ↓ Comerciantes en establecimientos | observado: 2,084 | esperado: 2,276.13 | residual: -5.74
   ↓ Otros directores, funcionarios, gerentes, coordinadores y jefes de área, no clasificados anteriormente | observado: 67 | esperado: 112.83 | residual: -5.96
   ↓ Trabajadores en cuidados personales y del hogar | observado: 69 | esperado: 120.42 | residual: -6.47
   ↓ Otros trabajadores auxiliares en actividades administrativas, no clasificados anteriormente | observado: 56 | esperado: 106.67 | residual: -6.78
   ↓ Otros trabajadores en actividades elementales y de apoyo, no clasificados anteriormente | observado: 1 | esperado: 27.50 | residual: -6.97
   ↓ Empleados de ventas en establecimientos | observado: 54 | esperado: 107.62 | residual: -7.14
   ↓ Trabajadores de paquetería, de apoyo para espectáculos, mensajeros y repartidores de mercancías | observado: 9 | esperado: 46.94 | residual: -7.64
   ↓ Auxiliares y técnicos en ciencias exactas, biológicas, ingeniería, informática y en telecomunicaciones | observado: 335 | esperado: 471.25 | residual: -8.71
   ↓ Trabajadores en servicios de protección y vigilancia | observado: 244 | esperado: 385.91 | residual: -10.02
   ↓ Trabajadores de apoyo en actividades agropecuarias, forestales, pesca y caza | observado: 230 | esperado: 374.06 | residual: -10.33
   ↓ Trabajadores domésticos, de limpieza, planchadores y otros trabajadores de limpieza | observado: 122 | esperado: 239.89 | residual: -10.53
   ↓ Conductores de transporte y de maquinaria móvil | observado: 817 | esperado: 1,067.66 | residual: -10.74
   ↓ Trabajadores de apoyo en la minería, construcción e industria | observado: 42 | esperado: 175.42 | residual: -13.92
   ↓ Trabajadores en la extracción y la edificación de construcciones | observado: 800 | esperado: 1,198.99 | residual: -16.16
   ↓ Ocupaciones insuficientemente especificadas | observado: 912 | esperado: 1,664.55 | residual: -26.05
   ↓ No aplica a menores de 5 años | observado: 1 | esperado: 432.37 | residual: -28.78

EstadoCivil:
   ↑ Viudo(a) | observado: 9,501 | esperado: 8,015.05 | residual: 25.98
   ↑ Casado(a) | observado: 13,331 | esperado: 11,809.71 | residual: 23.57
   ↓ Union Libre | observado: 2,552 | esperado: 3,430.55 | residual: -21.75
   ↓ Soltero(a) | observado: 7,501 | esperado: 9,085.08 | residual: -26.52
   ↓ No aplica a menores de 12 | observado: 1 | esperado: 497.80 | residual: -30.92


----------------------------------------------------------------------------------------------------
CAUSA: Agresion Con Disparo De Otras Armas De Fuego, Y Las No Especificadas, Calles Y Carreteras
----------------------------------------------------------------------------------------------------

Sexo:
   ↑ Hombre | observado: 10,791 | esperado: 6,868.91 | residual: 79.98
   ↓ Mujer | observado: 939 | esperado: 4,861.09 | residual: -79.98

AfroMexicanos:
   ↑ No especificado | observado: 902 | esperado: 553.27 | residual: 16.52
   ↓ Si | observado: 57 | esperado: 77.11 | residual: -2.50
   ↓ No | observado: 10,046 | esperado: 10,393.36 | residual: -10.98

CondicionIndigena:
   ↑ No especificado | observado: 1,172 | esperado: 608.04 | residual: 25.55
   ↓ No | observado: 9,544 | esperado: 9,769.96 | residual: -6.08
   ↓ Si | observado: 289 | esperado: 645.75 | residual: -15.71

Escolaridad:
   ↑ Secundaria completa | observado: 3,825 | esperado: 1,764.86 | residual: 57.88
   ↑ Bachillerato o preparatoria incompleto | observado: 797 | esperado: 257.55 | residual: 36.98
   ↑ Secundaria incompleta | observado: 945 | esperado: 342.58 | residual: 35.94
   ↑ Bachillerato o preparatoria completo | observado: 1,641 | esperado: 910.75 | residual: 27.41
   ↓ No especificado | observado: 175 | esperado: 331.72 | residual: -9.50
   ↓ No aplica a menores de 3 | observado: 5 | esperado: 127.38 | residual: -11.86
   ↓ Primaria completa | observado: 2,193 | esperado: 2,744.80 | residual: -13.09
   ↓ Primaria incompleta | observado: 887 | esperado: 2,508.04 | residual: -39.72
   ↓ Sin escolaridad | observado: 316 | esperado: 1,731.35 | residual: -40.08

Ocupacion:
   ↑ Trabajo elemental y apoyo | observado: 1,039 | esperado: 304.87 | residual: 46.35
   ↑ Construcción y manufactura | observado: 1,875 | esperado: 840.15 | residual: 40.31
   ↑ Operadores y transporte | observado: 1,008 | esperado: 387.57 | residual: 34.87
   ↑ Comercio y ventas | observado: 1,536 | esperado: 789.73 | residual: 29.92
   ↑ Servicios | observado: 504 | esperado: 209.15 | residual: 22.38
   ↑ Técnicos y auxiliares | observado: 470 | esperado: 228.54 | residual: 17.55
   ↑ Dirección y gerencia | observado: 115 | esperado: 48.87 | residual: 10.31
   ↑ Fuerzas armadas | observado: 33 | esperado: 7.60 | residual: 10.02
   ↑ Administrativos | observado: 154 | esperado: 83.78 | residual: 8.38
   ↓ No especificado / fuera de clasificación | observado: 3,807 | esperado: 7,561.52 | residual: -78.80

Ocupacion_Ampliado:
   ↑ Ocupaciones insuficientemente especificadas | observado: 1,876 | esperado: 544.74 | residual: 63.55
   ↑ Trabajadores en la extracción y la edificación de construcciones | observado: 1,097 | esperado: 392.38 | residual: 39.36
   ↑ Conductores de transporte y de maquinaria móvil | observado: 932 | esperado: 349.40 | residual: 34.43
   ↑ Trabajadores de apoyo en actividades agropecuarias, forestales, pesca y caza | observado: 412 | esperado: 122.42 | residual: 28.63
   ↑ Trabajadores de apoyo en la minería, construcción e industria | observado: 256 | esperado: 57.41 | residual: 28.59
   ↑ Comerciantes en establecimientos | observado: 1,422 | esperado: 744.89 | residual: 27.89
   ↑ Auxiliares y técnicos en ciencias exactas, biológicas, ingeniería, informática y en telecomunicaciones | observado: 375 | esperado: 154.22 | residual: 19.47
   ↑ Trabajadores en servicios de protección y vigilancia | observado: 310 | esperado: 126.29 | residual: 17.88
   ↑ Trabajadores de paquetería, de apoyo para espectáculos, mensajeros y repartidores de mercancías | observado: 70 | esperado: 15.36 | residual: 15.18
   ↑ Trabajadores domésticos, de limpieza, planchadores y otros trabajadores de limpieza | observado: 191 | esperado: 78.51 | residual: 13.86
   ↑ Artesanos y trabajadores en el tratamiento y elaboración de productos de metal | observado: 198 | esperado: 90.14 | residual: 12.41
   ↑ Otros trabajadores artesanales no clasificados anteriormente | observado: 389 | esperado: 222.18 | residual: 12.29
   ↑ Trabajadores en cuidados personales y del hogar | observado: 108 | esperado: 39.41 | residual: 11.91
   ↑ Ayudantes de conductores de transporte, conductores de transporte de tracción humana y animal y cargadores | observado: 45 | esperado: 10.86 | residual: 11.28
   ↑ Otros trabajadores en actividades elementales y de apoyo, no clasificados anteriormente | observado: 40 | esperado: 9.00 | residual: 11.25
   ↑ Otros trabajadores auxiliares en actividades administrativas, no clasificados anteriormente | observado: 95 | esperado: 34.91 | residual: 11.08
   ↑ Empleados de ventas en establecimientos | observado: 94 | esperado: 35.22 | residual: 10.79
   ↑ Trabajadores de la Armada, Ejército y Fuerza Aérea | observado: 33 | esperado: 7.60 | residual: 10.02
   ↑ Otros directores, funcionarios, gerentes, coordinadores y jefes de área, no clasificados anteriormente | observado: 83 | esperado: 36.93 | residual: 8.26
   ↑ Artesanos y trabajadores en la elaboración de productos de hule, caucho, plásticos y de sustancias químicas | observado: 21 | esperado: 5.59 | residual: 7.10
   ↑ Trabajadores en la preparación y servicio de alimentos y bebidas, así como en servicios de esparcimiento y de hotelería | observado: 86 | esperado: 43.44 | residual: 7.04
   ↑ Trabajadores en la elaboración y procesamiento de alimentos, bebidas y productos de tabaco | observado: 66 | esperado: 35.69 | residual: 5.53
   ↑ Funcionarios y altas autoridades de los sectores público, privado y social | observado: 12 | esperado: 3.41 | residual: 5.06
   ↑ Otros operadores de maquinaria industrial, ensambladores y conductores de transporte, no clasificados anteriormente | observado: 47 | esperado: 24.51 | residual: 4.95
   ↑ Ayudantes en la preparación de alimentos | observado: 9 | esperado: 2.48 | residual: 4.50
   ↑ Operadores de instalaciones y maquinaria industrial | observado: 27 | esperado: 13.19 | residual: 4.14
   ↑ Artesanos y trabajadores en la elaboración de productos de cerámica, vidrio, azulejo y similares | observado: 20 | esperado: 9.31 | residual: 3.81